services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --reload --proxy-headers --forwarded-allow-ips "*"
    volumes:
      - ./backend:/app
    container_name: backend
    environment:
      - POSTGRES_DB=boosty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  frontend:
    build: ./frontend
    command: uvicorn main:app --host 0.0.0.0 --reload --proxy-headers --forwarded-allow-ips "*"
    volumes:
      - ./frontend:/app
    container_name: frontend
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
    depends_on:
      - backend
      - frontend

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=boosty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: psql
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/

volumes:
  postgresql_volume: